# Generated by Django 2.1.3 on 2018-11-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_title', models.CharField(max_length=200)),
                ('n_content', models.CharField(max_length=200)),
                ('n_date', models.DateTimeField(verbose_name='date published')),
                ('n_is_publish', models.CharField(max_length=2)),
                ('n_category', models.CharField(max_length=2)),
            ],
        ),
    ]
