# Generated by Django 2.1.3 on 2018-11-06 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_news_n_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发表时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='n_category',
            field=models.CharField(max_length=2, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_is_publish',
            field=models.CharField(max_length=2, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
