# Generated by Django 2.1.3 on 2018-11-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20181106_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pub_date',
            new_name='create_dt',
        ),
    ]
