# Generated by Django 2.1.3 on 2018-11-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='n_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='n_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='n_is_publish',
            new_name='is_publish',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='n_title',
            new_name='title',
        ),
    ]
