# Generated by Django 2.1.3 on 2018-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20181106_1154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=20, verbose_name='分类'),
        ),
    ]
