# Generated by Django 2.1.3 on 2018-11-06 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
