# Generated by Django 2.1.3 on 2018-11-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
    ]
